#!/usr/bin/env python3
"""Extract CTW's code overlays and recompile each one.

CTW keeps its runtime-loaded code in WAD/OVERLAY/<build>/OVERLAYS.PAK: a "PK02"
sector archive whose payload is a sequence of "10SA" chunks
([magic][compressed size][uncompressed size][zlib stream]), each inflating to a
fixed-address ELF with one RWX section named ".overlay_<name>". This script

  1. extracts every overlay to <game>/overlays/<name>.elf,
  2. runs `psp_recomp --overlay` on each into <out>/<name>/ (namespace ovl_<name>),
  3. writes <out>/overlay_table.cpp: name, slot base, size, a 64-byte
     fingerprint and the registration function of every overlay, which the
     CTW host uses to register the corpus matching the code resident in a slot,
  4. regenerates the main corpus (--main-out) with the overlays as reference
     sources, so main-executable functions only overlays call become entries.
"""

import argparse
import re
import struct
import subprocess
import sys
import zlib
from pathlib import Path

FINGERPRINT_WORDS = 16
HOST_LOAD_BASE = "0x08804000"
UNIT_SPAN = "16384"


def overlay_chunks(pak: bytes):
    if pak[:4] != b"20KP":
        raise SystemExit("OVERLAYS.PAK: unexpected magic")
    position = 0
    while True:
        start = pak.find(b"10SA", position)
        if start < 0:
            return
        compressed, uncompressed = struct.unpack_from("<II", pak, start + 4)
        data = zlib.decompress(pak[start + 12:start + 12 + compressed])
        if len(data) != uncompressed:
            raise SystemExit(f"OVERLAYS.PAK: chunk at {start:#x} inflated to {len(data)}, expected {uncompressed}")
        yield data
        position = start + 12 + compressed


def describe(elf: bytes):
    """Returns (section name, vaddr, file bytes, memory size) of the overlay."""
    phoff, shoff = struct.unpack_from("<II", elf, 28)
    _, offset, vaddr, _, filesz, memsz, _, _ = struct.unpack_from("<8I", elf, phoff)
    shstrndx = struct.unpack_from("<H", elf, 50)[0]
    strtab_offset = struct.unpack_from("<I", elf, shoff + shstrndx * 40 + 16)[0]
    name_offset = struct.unpack_from("<I", elf, shoff + 40)[0]
    name = elf[strtab_offset + name_offset:].split(b"\0")[0].decode()
    return name, vaddr, elf[offset:offset + filesz], memsz


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--game", default="profiles/ctw/game", help="game root containing PSP_GAME/")
    parser.add_argument("--psp-recomp", default="out/framework-release/psp_recomp")
    parser.add_argument("--out", default="profiles/ctw/generated_overlays")
    parser.add_argument("--main-out", default="profiles/ctw/generated",
                        help="main corpus directory to regenerate ('' to skip)")
    args = parser.parse_args()

    game = Path(args.game)
    host = game / "PSP_GAME/SYSDIR/EBOOT_DECRYPTED.ELF"
    paks = sorted((game / "PSP_GAME/USRDIR/WAD/OVERLAY").glob("*/OVERLAYS.PAK"))
    if not paks:
        raise SystemExit("OVERLAYS.PAK not found under PSP_GAME/USRDIR/WAD/OVERLAY")
    overlay_dir = game / "overlays"
    overlay_dir.mkdir(parents=True, exist_ok=True)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    overlays = []
    for elf in overlay_chunks(paks[0].read_bytes()):
        section, vaddr, image, memsz = describe(elf)
        name = re.sub(r"[^A-Za-z0-9_]", "_", section.removeprefix(".overlay_"))
        if len(image) < FINGERPRINT_WORDS * 4:
            raise SystemExit(f"{name}: image too small to fingerprint")
        elf_path = overlay_dir / f"{name}.elf"
        elf_path.write_bytes(elf)
        overlays.append((name, vaddr, memsz, struct.unpack_from(f"<{FINGERPRINT_WORDS}I", image), elf_path))

    seen = {}
    for name, vaddr, _, fingerprint, _ in overlays:
        key = (vaddr, fingerprint)
        if key in seen:
            raise SystemExit(f"fingerprint collision in slot {vaddr:#x}: {seen[key]} and {name}")
        seen[key] = name

    for index, (name, _, _, _, elf_path) in enumerate(overlays, 1):
        print(f"[{index}/{len(overlays)}] {name}", flush=True)
        subprocess.run([args.psp_recomp, str(host), "--overlay", str(elf_path), str(out / name),
                        f"ovl_{name}", HOST_LOAD_BASE, UNIT_SPAN], check=True, stdout=subprocess.DEVNULL)

    lines = ['// Generated by profiles/ctw/tools/build_overlays.py. Do not edit.',
             '#include "ctw_overlays.hpp"', '', 'namespace psprecomp {']
    lines += [f'namespace ovl_{name} {{ void register_generated_functions(Runtime &runtime); }}'
              for name, *_ in overlays]
    lines += ['} // namespace psprecomp', '', 'namespace ctw {', '',
              f'const std::array<OverlayInfo, {len(overlays)}> kOverlays{{{{']
    for name, vaddr, memsz, fingerprint, _ in overlays:
        words = ", ".join(f"0x{word:08X}u" for word in fingerprint)
        lines.append(f'    {{"{name}", 0x{vaddr:08X}u, 0x{memsz:X}u, {{{{{words}}}}}, '
                     f'&psprecomp::ovl_{name}::register_generated_functions}},')
    lines += ['}};', '', 'std::span<const OverlayInfo> overlays() { return kOverlays; }', '',
              '} // namespace ctw', '']
    (out / "overlay_table.cpp").write_text("\n".join(lines))
    if args.main_out:
        print("regenerating main corpus with overlay references", flush=True)
        subprocess.run([args.psp_recomp, str(host), "--auto", args.main_out, HOST_LOAD_BASE, UNIT_SPAN,
                        *(str(path) for *_, path in overlays)], check=True)
    slots = sorted({vaddr for _, vaddr, *_ in overlays})
    print(f"{len(overlays)} overlays in {len(slots)} slots: {', '.join(hex(s) for s in slots)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
