#!/usr/bin/env python3
"""Compile the Vulkan GE shaders (src/hle/shaders) to SPIR-V and embed them.

Writes src/hle/ge_gpu_vulkan_shaders.inc, which is committed so building the
project does not need a shader compiler. Rerun after editing a shader:

    python3 tools/compile_vulkan_shaders.py   # needs glslc (shaderc)
"""

import struct
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHADER_DIR = ROOT / "src/hle/shaders"
OUTPUT = ROOT / "src/hle/ge_gpu_vulkan_shaders.inc"
SHADERS = [("ge.vert", "kGeVertexSpirv"), ("ge.frag", "kGeFragmentSpirv")]


def main():
    lines = ["// Generated by tools/compile_vulkan_shaders.py from src/hle/shaders. Do not edit.", ""]
    with tempfile.TemporaryDirectory() as scratch:
        for source, symbol in SHADERS:
            spirv = Path(scratch) / (source + ".spv")
            subprocess.run(["glslc", "-O", "--target-env=vulkan1.3", "-I", str(SHADER_DIR),
                            str(SHADER_DIR / source), "-o", str(spirv)], check=True)
            data = spirv.read_bytes()
            words = struct.unpack(f"<{len(data) // 4}I", data)
            lines.append(f"constexpr std::uint32_t {symbol}[] = {{")
            for i in range(0, len(words), 8):
                lines.append("    " + ", ".join(f"0x{w:08X}u" for w in words[i:i + 8]) + ",")
            lines += ["};", ""]
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
